// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkDt8iZbsqFTI6DizWmNOYy0zlkY6BCIc',
    appId: '1:1031422555705:web:863d951966cb0f74853fe8',
    messagingSenderId: '1031422555705',
    projectId: 'task-17bfa',
    authDomain: 'task-17bfa.firebaseapp.com',
    storageBucket: 'task-17bfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0sFm0y52HJO_0scg7KaNqj9NX1kFQxTQ',
    appId: '1:1031422555705:android:10bbcacfe4f906ba853fe8',
    messagingSenderId: '1031422555705',
    projectId: 'task-17bfa',
    storageBucket: 'task-17bfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrmfmguZ3cO0d68fZC5W8P6nZJFXDMRso',
    appId: '1:1031422555705:ios:17206374f8e6cc17853fe8',
    messagingSenderId: '1031422555705',
    projectId: 'task-17bfa',
    storageBucket: 'task-17bfa.appspot.com',
    iosBundleId: 'com.example.interviewTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrmfmguZ3cO0d68fZC5W8P6nZJFXDMRso',
    appId: '1:1031422555705:ios:17206374f8e6cc17853fe8',
    messagingSenderId: '1031422555705',
    projectId: 'task-17bfa',
    storageBucket: 'task-17bfa.appspot.com',
    iosBundleId: 'com.example.interviewTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkDt8iZbsqFTI6DizWmNOYy0zlkY6BCIc',
    appId: '1:1031422555705:web:95a635065507602f853fe8',
    messagingSenderId: '1031422555705',
    projectId: 'task-17bfa',
    authDomain: 'task-17bfa.firebaseapp.com',
    storageBucket: 'task-17bfa.appspot.com',
  );
}
